const productos = [
{
"title": "Libro El Nudo - Carlos Pagni - Planeta",
"price": 8900,
"image": ["https://http2.mlstatic.com/D_NQ_NP_2X_704082-MLA54749143699_032023-F.webp"],
"genre": ["Politica"],
"description":["Un territorio, el conurbano bonaerense, y una fecha concreta, la crisis de 2001, son, además de los protagonistas de este libro, las coordenadas que terminaron con un modelo de país y forjaron la Argentina que llega hasta el presente, la de una crisis sin final, con la degradación de la vida material como telón de fondo permanente y al parecer inevitable. 'El modelo económico que había entrado en convulsión estalló en el lugar donde se lo había fundado. El conurbano de la provincia de Buenos Aires', dice Carlos Pagni en el comienzo de estas páginas, que son el resultado de una indagación de cinco años. En la extraordinaria auscultación de ese temblor que supone El nudo, Pagni cruza sus dos juegos de herramientas: las del analista político mejor informado de la Argentina y las del historiador. Del mismo modo, aquí conviven dos libros: los grandes temas que caracterizan al conurbano (pobreza, clientelismo, hacinamiento, cuentapropismo, informalidad y fallas crónicas del Estado) y la historia de la conformación de ese territorio indómito, los hitos de la irrupción de la provincia de Buenos Aires en la política nacional, desde finales del siglo XIX hasta un tour de force final con el relato de 2001, porque, como dice el autor, 'la sociedad sigue atrapada en una agenda de problemas que se inauguraron en medio de esa gran alteración'."],
"id": 50000},
{
"title": "Libro La Hipótesis Del Amor - Ali Hazelwood - Contraluz",
"price": 7760,
"image": ["https://http2.mlstatic.com/D_NQ_NP_2X_846514-MLA49706659378_042022-F.webp"],
"genre":["Novela"],
"description":["Una relación falsa entre dos científicos se topa con la irresistible fuerza de la atracción. Olive Smith es una estudiante de doctorado que no cree en las relaciones amorosas duraderas, pero su mejor amiga, Ahn, sí, y por eso Olive se ha metido en un lío monumental. A Ahn le gusta el exnovio de Olive, pero jamás daría el primer paso porque es una buena amiga. Convencerla de que lo pasado pasado y de que está construyendo su «fueron felices para siempre» no va a resultarle nada fácil a Olive, puesto que los científicos necesitan pruebas. Por eso, como cualquier mujer con un mínimo de amor propio, se deja llevar por el pánico y besa al primer hombre con el que se encuentra para que Ahn la vea. Ese hombre es nada más y nada menos que Adam Carlsen, un joven profesor tan reputado por la calidad de su trabajo como por su arrogancia. Así que Olive se queda de piedra cuando Carlsen accede a mantener su farsa en secreto y ser su novio falso. Sin embargo, después de que un importante congreso científico se convierta en un desastre y Adam vuelva a sorprenderla con su apoyo inquebrantable (y sus inquebrantables abdominales), su pequeño experimento se acerca peligrosamente al punto de combustión. Olive no tarda en descubrir que la única cosa más complicada que una hipótesis sobre el amor es analizar su propio corazón bajo el microscopio."],
"id": 50001},
{
"title": "Espada, Tres Espejos - Sebastian Vargas",
"price": 2800,
"image": ["https://http2.mlstatic.com/D_NQ_NP_2X_687242-MLA51543294707_092022-F.webp"],
"genre":["Cuentos"],
"description":["Jian Deyán, campesino de un pueblo de la antigua China, se enamora de Yue Chan, la hija del herrero del pueblo. Una rebelión contra el emperador hace que la pareja deba separarse. Juran reencontrarse en la Fiesta de los Faroles, pero luego de que los rebeldes matan a su padre, solo le queda huir nadando por el mar, hasta que es rescatado por el Ceja Verde, un barco pirata. Aunque él mismo se convierte en pirata, y en capitán, el recuerdo de Yue es poderoso, por lo que decide abandonar todo e ir en su búsqueda. Si bien puede abordarse en forma independiente, con Tres Espejos. Luna la obra adquiere riqueza en los modos de leer. Obra ganadora del premio El Barco de Vapor 2012."] ,
"id": 50002},
{
"title": "Cartas A Quien Pretende Enseñar - Freire, Paulo",
"price": 3190,
"image": ["https://http2.mlstatic.com/D_NQ_NP_2X_816708-MLA51743087622_092022-F.webp"],
"genre":["Pedagoía"],
"description":["Un libro es una fuente de aprendizaje e imaginación. Permite conocer, descubrir y explorar el mundo que nos rodea. Aumenta nuestra curiosidad y nos mantiene entretenidos. Los libros nos permiten conectar con historias, personajes y sentimientos ayudando a nuestra comprensión, vocabulario y escritura."],
"id": 50003},
{
"title": "La Verdad Sobre El Caso Harry Quebert",
"price": 11099,
"image":["https://http2.mlstatic.com/D_NQ_NP_2X_704930-MLA32758317584_112019-F.webp"],
"genre":["Novela"],
"description":["La verdad sobre el caso Harry Quebert es una novela escrita por el suizo Joël Dicker, publicada en francés en septiembre de 2012 y editada en español en junio del año siguiente. Tras haber sido consagrada como la ganadora del Gran Premio de Novela de la Academia Francesa y el Prix Goncourt des Lycéens, se convirtió en un superventas mundial y se ha traducido a más de 33 idiomas. En 2015 publicó El libro de los Baltimore, novela también protagonizada por Marcus Goldman. Durante 2017 se rodó una miniserie de 10 episodios del mismo nombre basada en el libro de Dicker, producida por MGM para Epix, dirigida por Jean-Jacques Annaud. Se estrenó en octubre de 2018."],
"id": 50004},
{
"title": "El Camino Del Yoga - Libro Y 54 Cartas Óraculo - Sahara Rose",
"price": 13100,
"image":["https://http2.mlstatic.com/D_NQ_NP_645345-MLA47818901595_102021-O.webp"],
"genre":["Esoterismo"],
"description":["Esta visionaria baraja de 54 cartas está imbuida de la antigua sabiduría de los Vedas y ha sido diseñada para darte acceso a tu intuición yóguica. Las etéreas imágenes que ilustran sus cartas te ayudarán a comprender el presente y te orientarán sobre el futuro, conectándote con tu sabiduría interior y abriéndote a una comprensión más profunda de quién eres y cuál es tu realidad. El libro que la acompaña aporta descripciones completas de las cartas junto con indicaciones para trabajar con ellas, permitiéndote acceder a significados sagrados y recibir la intuición cósmica del universo"],
"id": 50005},
{
"title": "Libro Medico Medium Zumo De Apio ",
"price": 8400,
"image":["https://http2.mlstatic.com/D_NQ_NP_807055-MLA47864561694_102021-O.webp"],
"genre":["Medicina"],
"description":["Quinto volumen de la serie MÉDICO MÉDIUM RECUPERA TU VIDA CON LA ÚNICA GUÍA DEFINITIVA DEL ZUMO DE APIO El zumo de apio está salvando vidas y recuperando la salud de miles de personas. El hecho de que numerosas celebridades cuenten que toman esta bebida a diario, o de que gente de todo el mundo comparta imágenes y testimonios de sus espectaculares recuperaciones, revela que el zumo de apio es el pilar de un movimiento de curación realmente revolucionario. Anthony William lleva muchos años afrmando que esta bebida es una poderosa arma curativa que supera a cualquier superalimento, y que es justamente lo que necesitamos para atajar las enfermedades derivadas de nuestra forma de vida actual."],
"id": 50006},
{
"title": "Libro El Despertar - Kate Chopin - Erizo",
"price": 3200,
"image":["https://http2.mlstatic.com/D_NQ_NP_967571-MLA54244366905_032023-O.webp"],
"genre":["Novela"],
"description":["El despertar narra el progresivo acercamiento a la libertad de Edna Pontellier; mujer casada con un rico comerciante de Nueva Orleans y madre de dos hijos. Durante unas vacaciones en Grand Isle, en la costa sur de Luisiana, Edna empieza a conocerse como mujer y su vida, tal y como la ha concebido hasta ese momento, comienza a carecer de sentido. Su decisión de cambiar las cosas por completo le acarreará la incomprensión de sus amistades y su propio marido, incapaces todos de reconocer la nueva mujer que se ha despertado en el alma de Edna."],
"id": 50007},
{
"title": "Cuentos De Aprendizaje (2/ed.) - Del Mirador",
"price": 1850,
"image":["https://http2.mlstatic.com/D_NQ_NP_847597-MLA31474267523_072019-O.webp"],
"genre":["Cuentos"],
"description":["Es la infancia feliz un mito al que no queremos renunciar? Los pequeños protagonistas de los cuentos que forman esta antología descubren, muy tempranamente, la mentira, el abandono, la desilusión amorosa, las contradicciones y la hostilidad del mundo de los adultos.La tensa escritura de Liliana Heker, Antonio Dal Masetto, Daniel Moyano, Silvina Ocampo, Abelardo Castillo, María Esther de Miguel, Marcelo Birmajer y Julio Cortázar nos trae paisajes familiares, personajes cercanos y voces íntimas, porque son los que constituyen el entramado de nuestra sociedad.La lectura de estos relatos se propone como una experiencia de aprendizaje, para reflexionar acerca de la necesidad de transformar la agresión en ternura, la ausencia en presencia, la soledad en compañía y la discriminación, en abierta tolerancia."],
"id": 50008},
{
"title": "Intrigas En El Virreinato",
"price": 1950,
"image":["https://http2.mlstatic.com/D_NQ_NP_983950-MLA40528405603_012020-O.webp"],
"genre":["Infantil"],
"description":["Pól Kelly, un espía irlandés encubierto al servicio de la Corona británica, está a punto de ser fusilado. En su última noche recuerda lo sucedido en estas tierras durante las invasiones inglesas, la Revolución de mayo y la gesta de la Independencia"],
"id": 50009},
{
"title": "Libro El Retrato De Dorian Gray - Oscar Wilde - Alma",
"price": 2890,
"image":["https://http2.mlstatic.com/D_NQ_NP_753760-MLA50333590996_062022-O.webp"],
"genre":["Clásica"],
"description":["En esta novela, Oscar Wilde indaga sobre el mito de la eterna juventud, al recrear el tema de un pacto diabólico para conservar la belleza y permanecer eternamente joven.Dorian Gray, un joven rico y de extraordinaria hermosura, descubre en plena era victoriana, tras haber sido pintado en un cuadro, la tristeza que sería envejecer. Entonces, desea que esto no ocurra jamás. Este deseo se traduce en un pacto que lleva a Dorian a cometer todo tipo de atrocidades, hasta llegar al crimen.El retrato de Dorian Gray es una extensa alegoría que sondea las profundidades del ser humano y cuya vigencia sorprende en cada nueva lectura de esta magistral obra."],
"id": 50010},
{
"title": "Ladran Sancho - Del Mirador - Cantaro",
"price": 1850,
"image":["https://http2.mlstatic.com/D_NQ_NP_675234-MLA46959614002_082021-O.webp"],
"genre":["Clásica"],
"description":["En un lugar de la Mancha cuyo nombre no puedo recordar; comenzó en 1605 una historia que no ha cesado de transcurrir. Por los caminos de España; un caballero enjuto y su lozano escudero avanzan al encuentro de aventuras. Los aguardan encantadores y gigantes; doncellas disfrazadas y maleantes encadenados. Enfrentan leones furiosos; falsos caballeros y auténticos malhechores. Alternan con aristócratas ociosos y con moros cautivos. Vencidos por el desengaño; regresan finalmente a la aldea de nombre ignorado. A partir de entonces; miles de lectores han continuado el itinerario trazado por Miguel de Cervantes; que los invitamos a compartir con esta nueva edición de El ingenioso hidalgo don Quijote de la Mancha."],
"id": 50011},
{
"title": "Cuentos Clasicos Para Soñar Felices - Peppa Pig",
"price": 3299,
"image":["https://http2.mlstatic.com/D_NQ_NP_992755-MLA54122588811_032023-O.webp"],
"genre":["Infantil"],
"description":["Peppa Pig te da las buenas noches con estos tres cuentos clásicos mundialmente conocidos pero protagonizados por ella, su familia y sus amigos. Hazle un hueco en tus sueños a las calabazas mágicas y los zapatos de cristal para evitar las rosas con espinas y al lobo feroz. La hora mágica comienza entre la aventuras de este libro y tu almohada."],
"id": 50012},
{
"title": "El Bosque De Los Siete Echizos - Liliana Cinetto",
"price": 2500,
"image":["https://http2.mlstatic.com/D_NQ_NP_824541-MLA50545941841_072022-O.webp"],
"genre":["Novela"],
"description":["Erase una vez un bellisimo bosque; protegido por los hechizos de siete brujas muy poderosas. Todos sus habitantes vivian felices hasta que algo terrible e inesperado ocurrio. Dalmacia; la unica heredera de las antiguas brujas; acudira al rescate junto a su secretaria; la lechuza Tiberia"],
"id": 50013},
{
"title": "Libro El Principio Del Corazón - Helen Hoang - Titania",
"price": 4250,
"image":["https://http2.mlstatic.com/D_NQ_NP_877923-MLA54078696480_022023-O.webp"],
"genre":["Novela"],
"description":["La carrera de violinista de Anna Sun toma un gran impulso cuando un vídeo suyo se vuelve viral en las redes sociales, pero ahora la presión del exito la bloquea cuando intenta replicar el momento. Y cuando su novio de toda la vida anuncia que quiere una relación abierta antes de establecer un compromiso definitivo, Anna, herida y enfadada, toma una determinación: si el quiere explorar otras opciones, ella tambien lo hará. Por eso decide embarcarse en una serie de citas de una noche. Cuanto más inaceptables sean los hombres, mejor."],
"id": 50014},
{
"title": "Luna Roja - Miranda Gray - Libro - Gaia - En Dia", 
"price": 6300,
"image":["https://http2.mlstatic.com/D_NQ_NP_735824-MLA43461266593_092020-O.webp"],
"genre":["Autoayuda"],
"description":["Miranda Gray nos explica que cada mujer dispone de una naturaleza cíclica única, y nos guía para vivir de forma apasionada y creativa basándonos en nuestros ciclos personales, a la vez que explora la conciencia femenina encerrada en la sabiduría ancestral, la mitología y los cuentos tradicionales occidentales, sugiriendo ejercicios y métodos prácticos (incluido el Diagrama Lunar) que facilitan la exploración del profundo significado de ser una Mujer Cíclica."],
"id": 50015},
{
"title": "La Encomienda - Margarita García Robayo - Anagrama",
"price": 3950,
"image":["https://http2.mlstatic.com/D_NQ_NP_608335-MLA40301840348_012020-O.webp"],
"genre":["Contemporaneo"],
"description":["Una inquietante novela sobre la incertidumbre, los recuerdos, los miedos, la soledad, las relaciones familiares y los anhelos de futuro. La narradora de estas páginas vive a cinco mil kilómetros de su país natal, trabaja para una agencia de publicidad, quiere tramitar una beca para irse a escribir a Holanda y mantiene periódicas videoconferencias con su hermana. Esta le manda encomiendas, paquetes que incluyen comida, dibujos de sus sobrinos y de vez en cuando alguna sorpresa, como una vieja fotografía. A menudo la comida llega podrida. Una serie de figuras y acontecimientos irán dejando entrever las fisuras que se abren en la cotidianeidad de la protagonista: la recepción de una enorme caja difícil de abrir, una gata que se pasea por el edificio en el que vive, los vecinos que se ausentan y los que llaman a su puerta, el hijo de una vecina, las idas y venidas de su novio, un vagabundo... Y es que, como ella misma dice: ´Con qué rapidez se hace pedazos la cáscara de una rutina. Cualquier rutina, por sólida que sea, es arrasada por lo imprevisto.´ Con mano maestra y notable economía de medios, Margarita García Robayo conduce al lector por el laberinto de su protagonista y narradora en esta inquietante novela que habla de incertidumbre, recuerdos, miedos, soledad, relaciones familiares, perspectivas de maternidad y anhelos de futuro. Un libro de contenida intensidad, repleto de atisbos más que de certezas, que confirma a la autora como una de las voces de la actual narrativa latinoamericana."],
"id": 50016},
{
"title": "Libro Cofre Y Burundi - De Osos Dormidos Y Hogares Perdidos",
"price": 11490,
"image":["https://http2.mlstatic.com/D_NQ_NP_874842-MLA52668238432_112022-O.webp"],
"genre":["Infantil"],
"description":["Burundi suena como un juego; un encuentro de letras fortuito. Como los encuentros de estos animales en las historias de esta colección de cuentos. De osos dormidos y hogares perdidos Oso se quedó profundamente dormido y no imagina que cuando despierte habrá llegado a un lugar desconocido. Esta nueva historia del mundo Burundi incluye un peluche del protagonista de la historia"],
"id": 50017},
{
"title": "Libro Curioso Incidente Del Perro A Medianoche - Haddon, Mar",
"price": 4399,
"image":["https://http2.mlstatic.com/D_NQ_NP_827564-MLA54287343103_032023-O.webp"],
"genre":["Novela"],
"description":["El curioso incidente del perro a medianoche es una novela que no se parece a ninguna otra. Elogiada con entusiasmo por autores consagrados como Oliver Sacks e Ian McEwan, ha merecido la aprobación masiva de los lectores en todos los países donde se ha publicado, además de galardones como el Premio Whitbread y el Premio de la Commonwealth al Mejor Primer Libro."],
"id": 50018},
{
"title": "La Naturaleza Del Deseo - Carla Guelfenbein",
"price": 6399,
"image":["https://http2.mlstatic.com/D_NQ_NP_944347-MLA52639992349_112022-O.webp"],
"genre":["Novela"],
"description":["No hay delirio más voraz que el deseo. Se alimenta de lo que encuentra, de lo que sabe y no sabe, crece mejor en las sombras, en los santuarios prohibidos, en las distancias insalvables."],
"id": 50019},
{
"title": "Libro Donde Se Acaba El Viento - Aa Vv",
"price": 2400,
"image":["https://http2.mlstatic.com/D_NQ_NP_634519-MLA48067501261_102021-O.webp"],
"genre":["Infantil"],
"description":["Un libro es una fuente de aprendizaje e imaginación. Permite conocer, descubrir y explorar el mundo que nos rodea. Aumenta nuestra curiosidad y nos mantiene entretenidos. Los libros nos permiten conectar con historias, personajes y sentimientos ayudando a nuestra comprensión, vocabulario y escritura."],
"id": 50020},
{
"title": "Lilah - El Juego Del Autoconocimiento",
"price": 7200,
"image":["https://http2.mlstatic.com/D_NQ_NP_657678-MLA29333378535_022019-O.webp"],
"genre":["Autoayuda"],
"description":["En el principio habitamos en la simple y perpetua Totalidad. Luego la Gran Mano nos soltará y nos deslizaremos hacia el Juego Divino. El azar; a través del dado de la memoria kármica; se unirá a nuestras vibraciones y nos llevará por una travesía única recorriendo las 8 estaciones del Lilah"],
"id": 50021},
{
"title": "Tres Monedas",
"price": 3600,
"image":["https://http2.mlstatic.com/D_NQ_NP_964858-MLA28364600646_102018-O.webp"],
"genre":["Novela"],
"description":["Consiglio se atiene a sus elecciones con una coherencia que nunca resulta artificiosa.. Beatriz Sarlo . Tres son los personajes de esta historia y tambien tres son las monedas que insisten en marcarles el destino. Sin embargo, el deseo de una vida diferente los lleva a tomar decisiones difciles para romper con la apacible rutina. Jorge Consiglio, uno de los escritores ms premiados de la literatura argentina contempornea, compone con maestra los d erroteros de Marina Kezelman, una resolutiva meteorloga, Car l, un musico de orquesta alemn, y Amer, un taxidermista que i ntenta, cada da, dejar de fumar. Una novela inquietante que narra el momento exacto en el que sus protagonistas se miran al espejo y descubren que ya no se reconocen."],
"id": 50022},
{
"title": "El Oráculo Lenormand ( Libro + Baraja ) - Martina J. Gabler",
"price": 10690,
"image":["https://http2.mlstatic.com/D_NQ_NP_947159-MLA48050545562_102021-O.webp"],
"genre":["Esoterismo"],
"description":["Un libro es una fuente de aprendizaje e imaginación. Permite conocer, descubrir y explorar el mundo que nos rodea. Aumenta nuestra curiosidad y nos mantiene entretenidos. Los libros nos permiten conectar con historias, personajes y sentimientos ayudando a nuestra comprensión, vocabulario y escritura."],
"id": 50023},
{
"title": "Libro Argentina 2024-2027 - Juan Carlos De Pablo - Sudamericana",
"price": 5399,
"image":["https://http2.mlstatic.com/D_NQ_NP_655854-MLA53882807917_022023-O.webp"],
"genre":["Ficcion"],
"description":["Dedicado a quien gane las elecciones nacionales de este año y gobierne la Argentina entre 2024 y 2027, este libro se propone como un aporte a la política económica a ser aplicada en ese período. Con su personalísimo estilo y su inefable capacidad de hacer entendible, concreto y cotidiano lo que a priori puede presentarse como complicado, abstracto y lejano, Juan Carlos de Pablo condensa sus más de cincuenta años de experiencia y destila el conjunto a la vez indispensable e ineludible de cuestiones sobre las que el próximo gobierno necesariamente deberá fijar posición."],
"id": 50024},
{
"title": "El Fantasma De Canterville - Golú - Norma",
"price": 2700,
"image":["https://http2.mlstatic.com/D_NQ_NP_802959-MLA40789400012_022020-O.webp"],
"genre":["Ficcion"],
"description":["El fantasma de Canterville, con título original The Canterville Ghost, es una novela escrita por Oscar Wilde y publicada originalmente en 1887 en una revista en dos entregas y posteriormente publicada como libro en una recopilación de cuentos y relatos cortos de Oscar Wilde."],
"id": 50025},
{
"title": "Todo Lo Que Necesito Ya Existe - Rupi Kaur - Seix - Libro",
"price": 5100,
"image":["https://http2.mlstatic.com/D_NQ_NP_822654-MLA49423473535_032022-O.webp"],
"genre":["Poesía"],
"description":["Con una sensibilidad exquisita, rupi kaur aborda en todo lo que necesito existe ya en mí algunos de los temas por los que se dio a conocer con sus anteriores obras como el feminismo, el trauma, la pérdida o el amor, pero en esta ocasión da un paso más allá y revela, en un ejercicio único de generosidad y honestidad, experiencias muy personales como el modo en que ha lidiado los últimos años con la depresión, el éxito o la presión a la que se ha visto sometida. Capaz de traducir en palabras sensaciones y sentimientos complejos, exhibe además una notable sabiduría para desgranar males de nuestro tiempo como la autoexigencia, las enfermedades mentales o las relaciones tóxicas"],
"id": 50026},
{
"title": "Libro Un Principe Encantador - Cochrum, Alison",
"price": 4690,
"image":["https://http2.mlstatic.com/D_NQ_NP_739414-MLA54490982334_032023-O.webp"],
"genre":["Novela"],
"description":["Dev Deshpande siempre ha creído en los cuentos de hadas. Así que no es de extrañar que haya pasado toda su carrera creándolos en el reality show de citas Y comieron perdices. Como el productor más exitoso en la historia del programa, Dev siempre escribe la historia de amor perfecta para sus concursantes, incluso mientras su propia vida amorosa se desmorona. Pero entonces el programa incorpora al desacreditado prodigio de la tecnología Charlie Winshaw como su nueva estrella."],
"id": 50027},
{
"title": "Coleccion Emily Starr - Lucy Maud Montgomery",
"price": 12650,
"image":["https://http2.mlstatic.com/D_NQ_NP_878919-MLA53666372236_022023-O.webp"],
"genre":["Ficcion"],
"description":["Lucy Maud Montgomery creó a una de las representantes más conocidas de la niñez canadiense en Ana la de Tejas Verdes y todos los libros posteriores, pero Emily estaba más cerca de su propio corazón. Al igual que Ana, Emily es una niña de mente fuerte, inteligente e imaginativa que se queda sola y desprotegida en un mundo duro, en el que es recibida por adultos que, al menos inicialmente, son fríos y no le demuestran amor. Las dos niñas crecen en medio de las bellezas de la Isla del Príncipe Eduardo, ambas muy sensibles a los esplendores naturales y muy fantasiosas. Los hilos gemelos de luz y oscuridad, amor y crueldad, esperanza y desesperación se entrelazan en un patrón tan significativo como duradero."],
"id": 50028},
{
"title": "Asterix 13 - Asterix Y El Caldero - Rene Goscinny",
"price": 4350,
"image":["https://http2.mlstatic.com/D_NQ_NP_664704-MLA46586277579_072021-O.webp"],
"genre":["Infantil"],
"description":["Las aventuras del galo han vendido hasta el momento 350 millones de ejemplares en el mundo. ¡La Gran Colección sigue creciendo! En esta ocasión, Asterix tendrá que ingeniárselas para devolver el dinero que ha sido robado de un caldero."],
"id": 50029},
{
"title": "Sublime Objeto De La Ideologia - Zizek - Libro Siglo Xxi",
"price": 5490,
"image":["https://http2.mlstatic.com/D_NQ_NP_643846-MLA42139344971_062020-O.webp"],
"genre":["Filosofía"],
"description":["En esta obra, provocativa y original, Slavoj Zizek contempla el tema de la mediación humana en un mundo posmoderno. Desde el hundimiento del Titanic hasta La ventana indiscreta de Hichcock, desde las óperas de Wagner hasta la ciencia ficción, desde Alien hasta el chiste judío, los agudos análisis del autor exploran las fantasías ideológicas de completud y exclusión que elabora la sociedad humana."],
"id": 50030},
{
"title": "Libro Trastornos En La Sobremesa Literaria - Viñas, David",
"price": 6200,
"image":["https://http2.mlstatic.com/D_NQ_NP_777164-MLA54228380584_032023-O.webp"],
"genre":["Autoayuda"],
"description":["Trastornos en la sobremesa literaria reúne más de cin­cuenta artículos publicados por David Viñas a lo largo de casi tres décadas. Se trata de textos dispersos: aparecen en diarios y revistas de Argentina, Perú, México, España y Francia, entre 1974 y 2008, y mar­can el doble desplazamiento hacia el exilio y el re­torno a Argentina. Dispersos también en la medida en que se distancian del espacio literario propia­mente dicho para situarse en una zona amplia del debate cultural."],
"id": 50031},
{
"title": "El Gaucho Indomito - Ezequiel Adamovsky - Siglo Xxi - Libro",
"price": 5190,
"image":["https://http2.mlstatic.com/D_NQ_NP_776342-MLA50864944354_072022-O.webp"],
"genre":["Novela"],
"description":["Hace más de cien años que la figura del gaucho encarnada en Martín Fierro es el emblema central de la argentinidad. Hay algo desconcertante en eso: ¿cómo puede ser que nuestro héroe nacional sea un resentido con problemas de bebida que asesina sin razón a un compatriota? "],
"id": 50032},
{
"title": "Navegacion Astronomica Ne - Mederos Martin, Luis",
"price": 16971,
"image":["https://http2.mlstatic.com/D_NQ_NP_609025-MLA46286339821_062021-O.webp"],
"genre":["Ciencia"],
"description":["Este es un libro escrito para disfrutar aprendiendo a conocer el cielo y a utilizar esos conocimientos para obtener la posición del barco mediante la observación de los astros. Esta 7a edición, ampliada y actualizada, incluye más de 160 figuras, en su mayoría en color, lo que simplifica la visualización y el estudio de los planos, círculos y líneas; y en ella se utiliza una renovada definición del triángulo de posición que simplifica el manejo de este concepto en la práctica, reduciendo las fuentes típicas de error, haciendo innecesario recordar fórmulas y el uso de criterios de signos que pronto se olvidan.Además de ejercicios y ejemplos resueltos, en esta edición se ha añadido algo solicitado por muchos lectores: ejercicios tipo test como los que actualmente se proponen en los distintos exámenes para la obtención del título de Capitán de Yate. Tanto si eres estudiante de alguna titulación náutica, como si simplemente quieres meterte el cielo en la cabeza, encontrarás este libro sumamente interesante y fácil de leer."],
"id": 50033},
{
"title": "Libro Las Ondas De Elliott - Menendez Larre, Matias",
"price": 9090,
"image":["https://http2.mlstatic.com/D_NQ_NP_863984-MLA50449949610_062022-O.webp"],
"genre":["Economía"],
"description":["Existe una visión distorsionada sobre la inversión en los mercados financieros; motivada muchas veces por falsas recetas milagro para hacerse millonario y por tratarla como si fuera un juego de azar. La realidad de la inversión en los mercados financieros es completamente diferente y; sin duda; no se trata de una cuestión azarosa. Es posible hacer un seguimiento de los movimientos presentes del mercado y pronosticar los futuros con cierta exactitud; ya que dentro del caos que representan; existe un orden. La Teoría del Caos; la geometría fractal y el principio de las Ondas de Elliott nos permiten encontrar ese orden; que; junto con la ayuda de unos indicadores técnicos; eliminan la subjetividad hasta ahora existente."],
"id": 50034},
{
"title": "Tan Cerca, Totalmente Otro - Jullien, Francois",
"price": 3600,
"image":["https://http2.mlstatic.com/D_NQ_NP_883664-MLA54651728362_032023-O.webp"],
"genre":["Ficcion"],
"description":["¿No pasamos nuestra vida en la búsqueda insatisfecha del Otro? Del otro que al fin sea otro.Pero lo totalmente otro no tiene que aguardarse de ningún Allá esperado, de una lejanía fantaseada: el pensamiento no dejará nunca de girar en círculos en ese imaginario proyectado."],
"id": 50035},
{
"title": "El Estoque De Mango De Plata - Azulejos Rojo",
"price": 1850,
"image":["https://http2.mlstatic.com/D_NQ_NP_985012-MLA46759944376_072021-O.webp"],
"genre":["Novela"],
"description":["Tres amigos y una historia de amor y de traición en medio de los tiempos revueltos de la Independencia Nacional. Una novela para conmoverse y viajar en el tiempo a la etapa fundacional de la Argentina."],
"id": 50036},
{
"title": "Libro Años Salvajes - William Finnegan",
"price": 8150,
"image":["https://http2.mlstatic.com/D_NQ_NP_772672-MLA51196451586_082022-O.webp"],
"genre":["Novela"],
"description":["Años salvajes nos habla de una obsesión, la de William Finnegan con el surf. Finnegan comenzó a hacer surf de pequeño en Hawái y California. En los años setenta, tras finalizar sus estudios universitarios, su pasión le llevó a dejarlo todo y emprender un viaje iniciático por Samoa, Indonesia, Fiyi, Java, Australia y Sudáfrica. Este precario y singular viaje, por tierras cada vez más salvajes, y en el que varias veces estuvo al borde de la muerte, terminó llevándolo de vuelta a su país, donde se convertiría en un reconocido escritor y corresponsal de guerra. En Estados Unidos, pese a su nuevo trabajo, su pasión por las olas se mantiene intacta: continúa su búsqueda de la ola perfecta -la más grande, la más rápida, la más peligrosa- en San Francisco, la Costa Este o Madeira. Una búsqueda incesante que es, también, la del sentido de su existencia. Galardonado con el premio Pulitzer 2016, Años salvajes es una fascinante historia de aventuras y una autobiografía literaria de primerísimo nivel. Es, además, y sin ningún género de dudas, el mejor libro sobre surf que se haya escrito nunca."],
"id": 50037},
{
"title": "Cartas Oraculo De Las Vidas Pasadas Doreen Virtue",
"price": 8700,
"image":["https://http2.mlstatic.com/D_NQ_NP_815689-MLA46957002729_082021-O.webp"],
"genre":["Esoterismo"],
"description":["¿Quién eras en una vida pasada?, tu alma eterna ha vivido otras vidas que afectan tu carrera profesional, tu salud, tus relaciones, tu familia e incluso las lecciones que aprendes de la vida. Doreen Virtue y Brian Weiss se han unido para crear una herramienta sencilla, segura y agradable con la que podrás desentrañar los mensajes relacionados con tus vidas anteriores."],
"id": 50038},
{
"title": "Fundamentos De Nutricion En El Deporte 3ra.ed.",
"price": 6400,
"image":["https://http2.mlstatic.com/D_NQ_NP_920321-MLA45658826767_042021-O.webp"],
"genre":["Pedagoía"],
"description":["Desde 1997 ha ejercido la docencia de Nutrición y Deporte en la UBA, el CEMIC, la Universidad UNIDA de Paraguay, la Sociedad Española para Estudio-Avance de la Nutrición y Dietética Deportiva, el International Endurance Group (IEG), la Universidad del Salvador y la Universidad Abierta Interamericana."],
"id": 50039},
{
"title": "Libro Antología Poética - Alfonsina Storni - Del Fondo",
"price": 5130,
"image":["https://http2.mlstatic.com/D_NQ_NP_951179-MLA51244799280_082022-O.webp"],
"genre":["Poesía"],
"description":["'Antología Poetica - Alfonsina Storni En 1938, año de su muerte, apareció Antología Poetica, que ha quedado como un texto de referencia de una poeta que abandonó pronto un modernismo ya crepuscular para explorar un realismo existencial de exquisita sensibilidad y amplio registro basado en su propia experiencia."],
"id": 50040},
{
"title": "Las Canciones De Constanza - Antonio Santa Ana",
"price": 3100,
"image":["https://http2.mlstatic.com/D_NQ_NP_779814-MLA46957896073_082021-O.webp"],
"genre":["Infantil"],
"description":["Las canciones de Constanza es una novela de la escritora chilena Carla Guelfenbein, publicada en 2011. La historia se centra en Constanza, una famosa cantante de origen chileno que vive en Francia. A pesar de su éxito, Constanza esconde un oscuro secreto que ha marcado su vida y que ha influido en su música."],
"id": 50041},
{
"title": "After Tarot (78 Cartas + Manual) (estuche) - Alligo Pietro",
"price": 5400,
"image":["https://http2.mlstatic.com/D_NQ_NP_732270-MLA32844867588_112019-O.webp"],
"genre":["Esoterismo"],
"description":["After Tarot es un mazo de cartas de tarot creado por los artistas Pietro Alligo y Giulia F. Massaglia, y publicado en 2016. Este mazo de cartas presenta una continuación a las imágenes y simbolismos del mazo clásico de Tarot, permitiendo a los lectores profundizar aún más en las historias y arquetipos que se presentan en las cartas."],
"id": 50042},
{
"title": "Libro El Test Del Amor - Helen Hoang - Titania",
"price": 4250,
"image":["https://http2.mlstatic.com/D_NQ_NP_886326-MLA54092146738_032023-O.webp"],
"genre":["Novela"],
"description":["El Test del Amor de Helen Hoang, publicado por la editorial Titania, es una novela romántica contemporánea. Este género se caracteriza por presentar una trama centrada en el desarrollo de una relación amorosa entre los protagonistas, con elementos como el drama, el conflicto y la tensión romántica. La novela se enfoca en la historia de Khai, un joven autista que cree que no es capaz de enamorarse, y Esme, una chica vietnamita que llega a Estados Unidos en busca de una mejor vida para su familia. Juntos, enfrentarán diversos obstáculos y descubrirán el verdadero significado del amor."],
"id": 50043},
{
"title": "Siete Fantasticos Latinoamericanos - Generacion Z",
"price": 2100,
"image":["https://http2.mlstatic.com/D_NQ_NP_999230-MLU46103337723_052021-O.webp"],
"genre":["Biografía"],
"description":["Siete Fantásticos Latinoamericanos de Generación Z es un libro de no ficción que podría clasificarse en el género de biografías y ensayos. Este libro presenta perfiles biográficos de siete importantes escritores latinoamericanos del siglo XX: Julio Cortázar, Gabriel García Márquez, Carlos Fuentes, Octavio Paz, Mario Vargas Llosa, Pablo Neruda y Jorge Luis Borges. "],
"id": 50044},
{
"title": "Jugar Para Ganar - A. G. Lafley / Roger Martin",
"price": 4950,
"image":["https://http2.mlstatic.com/D_NQ_NP_799804-MLA52668281907_112022-O.webp"],
"genre":["Economía"],
"description":["Se centra en la estrategia de la empresa Procter & Gamble (P&G), de la cual A. G. Lafley fue director ejecutivo y presidente durante varios años. El libro ofrece una visión detallada de cómo Lafley y su equipo utilizaron estrategias específicas para transformar y revitalizar la empresa, convirtiéndola en una de las más exitosas del mundo."],
"id": 50045},
{
"title": "Albert Einstein - El Libro Definitivo De Citas - Calaprice",
"price": 9190,
"image":["https://http2.mlstatic.com/D_NQ_NP_870335-MLA45142823176_032021-O.webp"],
"genre":["Biografía"],
"description":["El libro definitivo de citas, es una colección de citas seleccionadas del famoso científico y pensador alemán Albert Einstein. El libro está organizado temáticamente, abarcando desde la física y la ciencia, hasta la política, la religión, la filosofía y la vida cotidiana."],
"id": 50046},
{
"title": "Tarot De La Diosa Triple  (cartas + Manual)  Lo Scarabeo",
"price": 5400,
"image":["https://http2.mlstatic.com/D_NQ_NP_933273-MLA52400366758_112022-O.webp"],
"genre":["Esoterismo"],
"description":["Tarot de la Diosa Triple, es un libro y juego de cartas diseñado por Isha Lerner que utiliza la imagen de la diosa triple como una herramienta para la adivinación y la exploración personal."],
"id": 50047},
{
"title": "Libro El Fin Del Autoodio - Virginia Gawel",
"price": 4860,
"image":["https://http2.mlstatic.com/D_NQ_NP_618853-MLA44803647874_022021-O.webp"],
"genre":["Autoayuda"],
"description":["La autora utiliza su propia experiencia personal y su formación como terapeuta para ayudar a los lectores a superar la autocrítica y el autodesprecio, y a construir una relación más amorosa y compasiva consigo mismos."],
"id": 50048},
{
"title": "Libro + Accesorios Un Día Con Rubén El Pingüino - Auzou",
"price": 4690,
"image":["https://http2.mlstatic.com/D_NQ_NP_648845-MLA31884392775_082019-O.webp"],
"genre":["Infantil"],
"description":["Este libro se presenta en una bolsa de pvc con cierre y manijas e incluye un juguete de baño que representa al protagonista de cada historia."],
"id": 50049}
]

export default productos;